apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: task-manager-api-pdb
  labels:
    app: task-manager
    component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: task-manager
      component: api
